import Navbar from "@/components/nabvar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { ThemeContext, ThemeProvider } from "../../context/ThemeContext";
import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const test: boolean = false;
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider>
          {/* <div
            className={`px-[200px] ${
              test ? "bg-red-700" : "bg-slate-900"
            }  text-white flex flex-col`}
          > */}
          <Navbar />
          {children}
          <Footer />
          {/* </div> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
